version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: Hema
      WORDPRESS_DB_PASSWORD: admin@123
      WORDPRESS_DB_NAME: Hemadb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: Hema
      MYSQL_PASSWORD: admin@123
      MYSQL_RANDOM_ROOT_PASSWORD: dbpass
    volumes:
      - db:/var/lib/mysql
    expose:
      - 3306
      - 33060

volumes:
  wordpress:
  db:
